### ISSUE TITLE
API Key Issues

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/google-map-gutenberg-block#13]
> For some reason I cannot get this Gmap addon to work.
> Using the same API key that works with ACF. Disabled ACF just to be sure API key is not called twice on page.
> Switched static map off. Adress suggestion does not work, map is not shown just empty space and console gives 403 Gmap error.

@StaggerLeee can you provide more information here? What is the error you are seeing in the console?

Also, note that Google Maps has multiple types of API keys/authorization. You can get the map embed API key [here](https://developers.google.com/maps/documentation/embed/get-api-key). My guess is your existing API key isn't authorized for map embeds and/or static map images.

**Comment by StaggerLeee** [comment]
Hi @ataylorme.
Console errors:

> Failed to load resource: the server responded with a status of 403 ()
> 18:08:48.142 googleads.g.doubleclick.net/pagead/id Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Is key not authorized to work with ACF embed maps ? Does ACF use embed maps ? Now I am confused.

It is generated for "HTTP referrers (websites)". I never saw any option for "static map images".

**Comment by StaggerLeee** [comment]
You can see here it is working fine for ACF.
I tried to disable ACF because it is not allowed to call the same API key twice on page, but it is the same.

![](https://s10.postimg.org/eym1qs9nd/2018-01-20_185001.jpg)

**Comment by StaggerLeee** [comment]
Strange it is working now. Maybe I missunderstood toogle option. Put some Info message inside block when "static image" is not working.
How do you configure API key for "static image" ? I never saw any option like this in API Dashboard.

Do not know if it is meant to be. Only ellipsis icon can activate right Block settings. Clicking on whole block does nothing.

**Comment by ataylorme** [comment]
@StaggerLeee your console error looks like an ad blocker or similar. Can you try an incognito window or something with browser extensions disabled?

Also, there are two APIs the plugin uses. The [embed API](https://developers.google.com/maps/documentation/embed/) for the interactive map (toggle on) and the [static map API](https://developers.google.com/maps/documentation/static-maps/) for the non-interactive map (toggle off).

It could be that your key is authorized for one or the other but needs to be authorized for both for everything to work properly.

**Comment by StaggerLeee** [comment]
OK. So it is one or another, not both ?

**Comment by ataylorme** [comment]
Probably but I'm not 100% sure. My first guess based on `ERR_BLOCKED_BY_CLIENT` is that it is an ad blocker or something else interfering.

If that's not the case and things still don't work without browser extensions and one map type, interactive or static, works but the other type does not then your API probably is only authorized for one but not both.

**Comment by StaggerLeee** [comment]
Can easy be this way. Disabled uBlock Chrome addon and errors are gone. I mean static toggle option works now, shows map.
Thank you. 

Maybe some task for you as developer. To find out why ad blocker lets ACF go with it, but not Gmap Gutenberg addon. Better to see what it is about now, than later deal with many Users and support questions. 

Or not, have no clue now. ACF does not have static image option, as I can remember now.

**Comment by ataylorme** [comment]
> Can easy be this way. Disabled uBlock Chrome addon and errors are gone. I mean static toggle option works now, shows map.
Thank you.

@StaggerLeee did the interactive map work for you before and it was just the static map that wasn't working?

> Maybe some task for you as developer. To find out why ad blocker lets ACF go with it, but not Gmap Gutenberg addon.

There are so many ad blocker apps/extensions I don't think it's feasible for me to test them all. Even if I did it would be up to the developers of the ad blocker to make it work with Google Maps.

**Comment by StaggerLeee** [comment]
Not at the first try. Later honestly do not know. As I missinterpreted toggle button and switched to static image map. So had no chance to know.

**Comment by ataylorme** [comment]
@StaggerLeee I have a pull request with [updated API key instructions](https://github.com/pantheon-systems/google-map-gutenberg-block/blob/18c786a4c8850126fb3106f167c6de33188bcb09/README.md). Can you can test out creating a key with this method and see if that helps?

I want to make sure the directions are correct and clear. Thanks

**Comment by StaggerLeee** [comment]
Hi. Instructions are very clear.

**Comment by ataylorme** [comment]
Great, thanks for checking. I'm going to close this out since the new instructions help
