### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/google-map-gutenberg-block#23]
I think this project needs a LICENSE file. Unless there's a reason to use something different, can you add the MIT one?

**Comment by ataylorme** [comment]
@davidstrauss [WordPress uses GPLV2 and suggests that plugins/themes use GPL as well](https://wordpress.org/about/license/). I think MIT would be okay too but GPL is more traditional for WordPress. Any objection to GPLV2?

**Comment by davidstrauss** [comment]
No objection to GPLv2 if that creates consistency with upstream. :-)

**Comment by ataylorme** [comment]
Closed by #24
