### ISSUE TITLE
Implement Gutenblock Design Virtues

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/google-map-gutenberg-block#8]
See [this comment](https://github.com/WordPress/gutenberg/issues/315#issuecomment-357620413)

- [x] Make location a pop-out field
- [x] Make block responsive

**Comment by ataylorme** [comment]
@jasmussen thanks so much for the comments over in the other thread. Moving to an issue here so we don't clutter that conversation.

I was able to use [the editable component](https://github.com/WordPress/gutenberg/blob/master/docs/blocks-editable.md) for the inline location field.

I ran into issues with the component's support for multiple lines and formatting as the string I send to Google maps can't contain markup such as `<br />`, `<strong>`, etc.

My solution is to strip these items from the value returned by the editable component before saving the value to the attribute. I'm not sure if this is the best approach but it works.

![gutenberg-google-map-embed-inline-location-field](https://user-images.githubusercontent.com/2133004/34965529-6335737a-fa09-11e7-94f3-f5287d9ff5a2.gif)

**Comment by ataylorme** [comment]
I guess I could swap `Editable` for `TextControl`

**Comment by jasmussen** [comment]
I'd absolutely use TextControl there, as bold/italic features are less useful in this situation. Love it!

**Comment by ataylorme** [comment]
@jasmussen I updated to use `TextControl` and removed the default location so users are prompted to enter one right away. The inline location field will hide if the block does not have focus and a location is entered but will remain, even if the block loses focus when a location is missing.

![google-map-block-demo](https://user-images.githubusercontent.com/2133004/35000196-9d07746a-fa98-11e7-92f9-e4c0a1b671f5.gif)

**Comment by jasmussen** [comment]
That looks really cool, nice work!

One thing that could be really cool — and this is for your idea pile — what if the block detected your current location using the browsers location API, and presented that as the _default_ map location? Then you'd essentially have a block with incredible defaults that worked right off the bat as soon as you inserted it, and only if you happened to need a different location would you need to change that location in the Text control.

**Comment by ataylorme** [comment]
> One thing that could be really cool — and this is for your idea pile — what if the block detected your current location using the browsers location API, and presented that as the default map location? Then you'd essentially have a block with incredible defaults that worked right off the bat as soon as you inserted it, and only if you happened to need a different location would you need to change that location in the Text control.

Let's create a new issue for that as an enhancement. I see it as a nice to have and not a must-have.

**edit** added: #11

**Comment by ataylorme** [comment]
@jasmussen updated to use aspect ratios and max width/height on the static image. Is this inline with what you envisioned?

![google-map-block-demo](https://user-images.githubusercontent.com/2133004/35008840-bc896f22-fab2-11e7-800f-9cc8e4c664bb.gif)

**Comment by jasmussen** [comment]
Yes, that aspect ratio is exactly what I had imagined, only cooler. This is 🔥

**Comment by ataylorme** [comment]
Great, glad you approve! I couldn't do aspect ratio on the static image since width and height are required and whatever value is entered I couldn't seem to override to the point the image was overflowing the parent element. I went with 100% width and auto height with setting for max width and max height as an alternative. Going to move forward with merging this in.
